### ISSUE TITLE
OEDT editor shows incorrect type

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#1]
When using a base class that is available in multiple USING statements, OpenEdge will use the first occurrence in the order of the USING statements.
The Progress editor shows the correct tooltip when hovering over the base type.
The OEDT editor seems to show the last occurrence instead.

![image](https://user-images.githubusercontent.com/8639525/43515598-267eafc6-9583-11e8-8a64-10a48f119cd3.png)

**Comment by lneumeier** [comment]
Verified and fixed in the next release.

![sorted-using](https://user-images.githubusercontent.com/39283158/43539662-c8c28086-95c5-11e8-9863-d38b9215b231.png)
