### ISSUE TITLE
Add configurable temp-table and buffer name prefix for coloring

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#100]
The site notes that Buffer and Temp-table coloring currently only works for "bf_" and "tt_".
These prefixes should be configurable.
Here we use "w_" (historic reasons, when using work tables), "b_" for buffers, and "wb_" for temp-table buffers...

**Comment by lneumeier** [comment]
Implemented in OEDT 9.3.4.
