### ISSUE TITLE
Smarter auto suggest

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#102]
When typing e.g.
`FOR EACH Order WHERE ` and then o + ctrl-space, all possible items beginning with o are shown alphabetically.
In this specific case I would expect "Order" to be highlighted/suggested, since that is logically what you would type there.
I'm sure other examples can be thought of that could benefit from some smarter auto suggest.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.3.5.
