### ISSUE TITLE
Jump from VisualDesigner with F9 opens OE ABL editor

### ISSUE THREAD

**Issue by orombauts** [omecra/de.omecra.oedt.updatesite#107]
Jump from VisualDesigner with F9 opens OE ABL editor, instead of the OEDT editor.
I found a closed issue on this, claiming it is fixed in 9.0.0 (Switch AppBuilder (question) #47), but for some reason it does not work for me.
I'm on version 9.3.5

**Comment by lneumeier** [comment]
Hello,

To quote myself:
"I can add SHIFT+F9 to open ABL UI Designer/Visual Designer, but F9 from the Visual Designer/ABL UI Designer seems to be hardcoded..."
