### ISSUE TITLE
Toggle comment on selected characters only

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#110]
I'm not sure if this is an OEDT or general Eclipse question, but is there a way to toggle comment (/* */) only for the selected characters?
Currently "toggle comment" seems to comment all characters from the current line, or when some text is selected from the beginning of the line until the end of the selection.

I would like to select a portion of a string and have that put in between comment signs using a shortcut.

**Comment by lneumeier** [comment]
Looks like a bug and i will fix it.

**Comment by lneumeier** [comment]
Fixed in 9.3.6.

If the selected text is on the same line, only the selected text is toggled as a comment, instead of the whole line.
