### ISSUE TITLE
Unused variables false positives

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#111]
See attached screenshot.
![image](https://user-images.githubusercontent.com/8639525/100841724-f9b3e100-3477-11eb-8a99-ba2dcb08fad6.png)

**Comment by lneumeier** [comment]
This issue is related to FGColor and BGColor as variable names, because they are standalone keywords. Im evaluating a solution for this kind of problem.

**Comment by lneumeier** [comment]
Fixed in 9.3.6.
