### ISSUE TITLE
Undetected variable occurrence - unused variable false positive

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#112]
2 issues with code below:
- when selecting Head, it isn't marked as occurrence in "OUTPUT Head"
- Class is flagged as unused variable (this might have been reported before).

![image](https://user-images.githubusercontent.com/8639525/104189336-d25b1700-541a-11eb-8620-17e3a77af0c2.png)

```
PROCEDURE MyProc:

    DEFINE VARIABLE Head AS CHARACTER NO-UNDO.
    DEFINE VARIABLE Class AS CHARACTER NO-UNDO.
    DEFINE VARIABLE Id AS CHARACTER NO-UNDO.

    /* --------------------------------------------------------------------- */

    RUN MyProc2(OUTPUT Head, OUTPUT Class, OUTPUT Id).
    RUN MyProc3(Head).

END PROCEDURE.
```

**Comment by lneumeier** [comment]
This issue is related to Class as variable name (breaking AST). I you change Class to ClassName the issue is gone.

In general, try to avoid using keywords as identifiers, especially keywords that describe/start code blocks like class, interface, method, constructor...

**Comment by PeterJudge-PSC** [comment]
> In general, try to avoid using keywords as identifiers, especially keywords that describe/start code blocks like class, interface,  method, constructor...

It's possible to avoid this, but OE does it with the `Progress.Lang.Class` type, and ABL classes like `OpenEdge.Core.Memptr` (yes, "progress" == me in this case but just to point out that you may not have control over those type names).

**Comment by lneumeier** [comment]
Variable or type names on its own is not a problem and there are no restrictions. The references in expressions (parameter for run statement) is a problem. In this case, if Class is a valid expression, then the parser can not decide, whether it is a starting CLASS-definition or a starting expression. This problem could be solved with context-awareness, but this would also slow down the parsing process...
