### ISSUE TITLE
Project facet de.omecra.oedt.ui.facet has not been defined

### ISSUE THREAD

**Issue by zipingwang** [omecra/de.omecra.oedt.updatesite#113]
Hi,
I got an error when exit Progress Developer Studio
![oedt facet has not been defined](https://user-images.githubusercontent.com/9693956/118263035-07a16f80-b4b6-11eb-977b-e151257facba.png)

"An error has occurred. See error log for more details.
Project facet de.omecra.oedt.ui.facet has not been defined."

My Oedt version is 9.3.6.  Progress Developer Studio is 4.5.2

**Comment by zipingwang** [comment]
Log file 
[
[.log](https://github.com/omecra/de.omecra.oedt.updatesite/files/6478653/default.log)
](url)

![Oedt Install](https://user-images.githubusercontent.com/9693956/118270028-b0a09800-b4bf-11eb-8251-8f2307d16773.png)
![Current installation](https://user-images.githubusercontent.com/9693956/118270187-f2314300-b4bf-11eb-8fe0-dace64942ba5.png)
![oedt plugin files](https://user-images.githubusercontent.com/9693956/118270356-3de3ec80-b4c0-11eb-9378-56271ea07696.png)

**Comment by zipingwang** [comment]
It has worked before, but suddenly no more, I don't know if you can help me?
Thanks in advance!

**Comment by lneumeier** [comment]
It looks like, that the plugin de.omecra.oedt.ui can't be loaded. This plugin defines the corresponding facet. 

java.io.IOException: Unable to resolve plug-in "platform:/plugin/de.omecra.oedt.ui/images/view/call_hierarchy.png".

You could try the following:
1. Close Oedt Call Hierarchy View
2. Close PDSOE
3. Remove from all de.omecra*.jar from %PDSOE-Location%\plugins
4. Remove all de.omecra* directories from %PDSOE-Location\features
5. Restart PDSOE with "-clean" option
6. Install OEDT from the update-site

**Comment by zipingwang** [comment]
I have followed your steps and reinstalled the oedt plugin.
I saw during the installation that oedt plugins files were prepared in oeide\eclipse\configuration\org.eclipse.osgi\335\data\572574558\plugins and features folder, but after installation there is no de.omecra.*.jar files in \oeide\eclipse\plugins folder.
also see attached video. 
Maybe something is wrong with my Progress Developer Studio.


https://user-images.githubusercontent.com/9693956/119134409-64b09e80-ba3d-11eb-8c3e-3953be9ab7ff.mp4

**Comment by lneumeier** [comment]
This is weird. Let's try it with a zip archive.

Close PDSOE, unzip the attached archive into %DLC%\oeide\eclipse (archive contains a plugins and features folder) and start PDSOE with the -clean option.
[oedt117-9.3.6.zip](https://github.com/omecra/de.omecra.oedt.updatesite/files/6548836/oedt117-9.3.6.zip)
