### ISSUE TITLE
Eclipse crashes when trying to use DocumentFormat.OpenXml (Open XML SDK)

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#114]
Hi,

I'm trying to get the Microsoft Open XML SDK running in ABL.

I've downloaded the nuget package [here](https://www.nuget.org/packages/DocumentFormat.OpenXml/), extracted the .NET 4.6 DocumentFormat.OpenXml.dll assembly from it and added it to a new empty workspace/project.

The moment I apply the OEDT facet to my project, Eclipse crashes while building the assembly model.
Afterwards I can no longer open the project/workspace without Eclipse crashing within seconds.

Without OEDT plugin OpenEdge seems to find the assembly and can do auto completion/add using statement, but even the simplest statement isn't compiling...

Do you have any idea what might be causing this, and if there's a workaround?

See [OE community thread](https://community.progress.com/s/question/0D54Q00008gdkmwSAA/has-anyone-successfully-used-open-xml-sdk-from-abl) as well.

Regards,
Lieven

**Comment by lneumeier** [comment]
Hello,

Unfortunately, there is little I can do. The .net bridge seems to have an issue with this assembly. As mentioned in the community thread, this error occurs in plain PDSOE while browsing through the "Class Browser" view to trigger the same API OEDT is using for reading the types and methods.
Plain PDSOE is loading assemblies on demand, while OEDT loads these assemblies on the first startup to build the model and to prevent potential delays during code assist.
