### ISSUE TITLE
Format code (more)

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#115]
I am missing 2 things compared to the default formatting of PDS:
- Multiple DEFINE statements are only indented, where the PDS builds a nice table (also not perfect, but much better than nothing).
- Multiple assignments in an ASSIGN. PDS formats this also as a nice table.

**Comment by lneumeier** [comment]
I will look into it.

**Comment by lneumeier** [comment]
I can't reproduce your case. OEDT and the PDSOE editor formatting the following code from
```
    DEFINE VARIABLE cTem AS CHARACTER NO-UNDO.
  DEFINE VARIABLE cfdhdgjj AS CHARACTER NO-UNDO.
DEFINE VARIABLE cdwlekl AS CHARACTER NO-UNDO.

DEFINE VARIABLE c AS CHARACTER NO-UNDO.
    DEFINE VARIABLE dds AS DECIMAL NO-UNDO.
          DEFINE VARIABLE lslfk AS LOGICAL NO-UNDO.

ASSIGN
  c = "1001"
      cTem = "sfmlkdf"
     dds = 122
      .

ASSIGN
        lslfk = FALSE
    cfdhdgjj = "kkddk"
          cdwlekl ="kslskdlsdk1!"
.
```
to
```
DEFINE VARIABLE cTem AS CHARACTER NO-UNDO.
DEFINE VARIABLE cfdhdgjj AS CHARACTER NO-UNDO.
DEFINE VARIABLE cdwlekl AS CHARACTER NO-UNDO.

DEFINE VARIABLE c AS CHARACTER NO-UNDO.
DEFINE VARIABLE dds AS DECIMAL NO-UNDO.
DEFINE VARIABLE lslfk AS LOGICAL NO-UNDO.

ASSIGN
  c = "1001"
  cTem = "sfmlkdf"
  dds = 122
  .

ASSIGN
  lslfk = FALSE
  cfdhdgjj = "kkddk"
  cdwlekl ="kslskdlsdk1!"
  .
```

**Comment by RobertHeintzCH** [comment]
I see what you mean.
I didn’t choose the right words.
It's not the formatting, it's the indentation.

With the Oedt Editor, we lost "Correct indentation Ctrl-i", so we were expecting "format source" to do that.

Can you add this?
