### ISSUE TITLE
Formatting bug 

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#117]
Formatting this code with Ctrl-Shift-F
IF ( 1 = 1 )    /* asssas */
THEN 
    .
IF ( 1 = 1 )    // asssas
THEN 
    .
IF ( 1 = 1 )    
THEN 
    .
ends like this
IF ( 1 = 1 )    /* asssas */      <<<<< Not folded (1)
THEN  
    .
IF ( 1 = 1 ) THEN      <<<< Comment lost !! (2)
    .
IF ( 1 = 1 ) THEN      <<<< folded correctly
    .

While (1) is not expected, it is acceptable.
But (2) is definitely not a good outcome.

**Comment by lneumeier** [comment]
OEDT is using the code formatter from PDSOE and the same behavior can be observed in the Progress Editor.
