### ISSUE TITLE
Format code (again)

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#119]
With the new version we have the menu item "Correct indentation" in the context menu, but it doesn't do anything.
When switching away from OEDT via "OpenWith => OpenEdge ABL Editor", the same menu item does it's job.

**Comment by lneumeier** [comment]
Which Openedge version are you using?

**Comment by RobertHeintzCH** [comment]
12.2.7

**Comment by lneumeier** [comment]
I will look into it.

**Comment by lneumeier** [comment]
Fixed in 9.4.0.

**Comment by RobertHeintzCH** [comment]
Thank you so much for this and the SERIALIZABLE fix.
Much appreciated!
