### ISSUE TITLE
"Recompile files that have errors" compiles .i - files

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#121]
Having some errors that come from compiling a .W, but the error itself being within an include, I used the "Recompile files that have errors" function in the problems view.
As you can see in the screenshot, this compiles the include file. 
I have never seen that happen in all the years before we had Oedt.

![image](https://user-images.githubusercontent.com/88428168/145988587-8abf9cef-eb80-4865-9d96-ecc174dbeea2.png)

**Comment by lneumeier** [comment]
"Recompile files that have errors" is a feature of PDSOE, not OEDT. Can post your preferences for 

- Preferences -> Oedt -> Compile 
- Preferences -> Progress OpenEdge -> Editor -> Build

and your .project file?

**Comment by RobertHeintzCH** [comment]
Oedt compile:
![image](https://user-images.githubusercontent.com/88428168/146124142-a430a7b3-0496-47be-a8a3-21b33a8243b4.png)

Editor Build:
![image](https://user-images.githubusercontent.com/88428168/146124224-4e65734f-76a8-4e40-8124-584b88d55ae4.png)

And this is the content of .project:
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>SourceZZ</name>
	<comment></comment>
	<projects>
		<project>Consultingwerk</project>
		<project>Source</project>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>de.omecra.oedt.OedtProjectBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.wst.common.project.facet.core.builder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>de.omecra.oedt.OedtProjectNature</nature>
		<nature>com.openedge.pdt.text.progressNature</nature>
		<nature>org.eclipse.wst.common.project.facet.core.nature</nature>
	</natures>
</projectDescription>

**Comment by RobertHeintzCH** [comment]
Sorry that went wrong. It's not easy to post the .project as content or as file ;) 
[project.zip](https://github.com/omecra/de.omecra.oedt.updatesite/files/7716514/project.zip)

**Comment by lneumeier** [comment]
The configuration looks good to me. Is this error reproducible?

**Comment by RobertHeintzCH** [comment]
I got it after some trial and error!

1. Add some error to an include.
2. Let OEDT dependency compile find the errors.
3. Suspend the OEDT compilation
4. Correct the error
5. Use the PDS-function "Recompile files with errors" from the Error view.
6. Now OEDT will take over the compilation and compile the include too

This is the console for the above steps:
[1/3/0] Include Changes
[06-01-2022 06:43:44] Compilation failed for /Source/Domus/Ablage/browser.w
                      /Source/Domus/Common/Output/Document/outDocumentActionHandler.i
[2/3/1] Include Changes
[06-01-2022 06:43:46] Compilation failed for /Source/Domus/Bline/Dokumentstruktur/UI/NavigationsBrowser.w
                      /Source/Domus/Common/Output/Document/outDocumentActionHandler.i
[3/3/2] Include Changes
[06-01-2022 06:43:47] Compilation failed for /Source/Domus/Katalog/Muster/browser.w
                      /Source/Domus/Common/Output/Document/outDocumentActionHandler.i
[06-01-2022 06:43:47] #Files: 3 #Failed: 3
[06-01-2022 06:46:53] /Source/Domus/Ablage/browser.w (D:\WS-trunk\Source\Domus\Ablage\browser.r)
**[06-01-2022 06:46:53] /Source/Domus/Common/Output/Document/outDocumentActionHandler.i (D:\WS-trunk\Source\Domus\Common\Output\Document\outDocumentActionHandler.r)**
[06-01-2022 06:46:55] /Source/Domus/Katalog/Muster/browser.w (D:\WS-trunk\Source\Domus\Katalog\Muster\browser.r)
[06-01-2022 06:46:59] /Source/Domus/Bline/Dokumentstruktur/UI/NavigationsBrowser.w (D:\WS-trunk\Source\Domus\Bline\Dokumentstruktur\UI\NavigationsBrowser.r)

And I have .R file for the include.

**Comment by lneumeier** [comment]
Thank you for your feedback.

I could reproduce the error, but it is the PDSOE functionality "Recompile files with errors" that is compiling include files, not OEDT. Please use the OEDT option "Compile Error Files".
OEDT compilation process have often a "Delta Changes" line before the source file and a summary at the end (number of files processed etc.)
