### ISSUE TITLE
OEDT database view

### ISSUE THREAD

**Issue by orombauts** [omecra/de.omecra.oedt.updatesite#122]
Hi,

Some suggestions for improvement:

- Is seems that fields in the OEDT database view are ordered in order of creation (oldest first).
This can be useful if you recently added a field to the table, but less practical when to have an alphabetical overview of the fields on that table. An option to toggle between the two modes would be nice
- Show uniqueness and sorting order on indexes
- An toggle option to show extra fields details next to the data type, like Format, Initial Value, Mandatory Y/N...

Kr

**Comment by lneumeier** [comment]
Thank you for your feedback.

> Is seems that fields in the OEDT database view are ordered in order of creation (oldest first).
This can be useful if you recently added a field to the table, but less practical when to have an alphabetical overview of the fields on that table. An option to toggle between the two modes would be nice

Currently, the fields are ordered by order number. Adding an option to sort alphabetical sounds good.

> An toggle option to show extra fields details next to the data type, like Format, Initial Value, Mandatory Y/N...

You can select a field and get some information in the properties view.

![oedtdatabase](https://user-images.githubusercontent.com/39283158/147158926-07bf5927-00fa-4a52-b539-3d63b5be555d.PNG)

**Comment by lneumeier** [comment]
Added in 9.4.0.

**Comment by orombauts** [comment]
Good job, helps a lot!
