### ISSUE TITLE
Following link of an external procedure when target does not have the .p extention

### ISSUE THREAD

**Issue by orombauts** [omecra/de.omecra.oedt.updatesite#123]
Hi,

My best wishes for 2022!

I have a question, but I'm not sure if this is something related to OEDT.

ABL allows you to run a procedure file like this:

RUN my_other_file.

Or like this:

RUN my_other_file.p

It seems that only the 2nd variant gives you a tool-tip hint and the possibility to open the file with CTRL+click.
We (MIPS) are tending to use the 1st variant. It would be helpful if that functionality also works for the 1st variant.

Thanks in advance for looking at this.

Kind regards,
Olivier

**Comment by lneumeier** [comment]
This is possible, but I'm not sure wether this is a good idea.

RUN statements without a file extension

- only works, if rcode is available (with separated src/rcode directory problematic)
- call an internal procedure, if one exists with the same name (super-procedures?, active persistent procedure?)

However, I will add an option/preference for "Open Declaration" / CTRL+Click.



RUN statements without a file extension only works for rcode-files. If an internal procedure is added with the same name, the internal

**Comment by lneumeier** [comment]
Added in 9.4.0.

**Comment by orombauts** [comment]
Works fine. Thanks a lot!
