### ISSUE TITLE
SERIALIZABLE not a reason for dependency compile

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#124]
I got errors on the build server that I didn't have in my development environment because I forgot SERIALIZABLE in a class.

I found that neither adding nor removing this option triggers a dependency compile.

CLASS test.Class1 
    SERIALIZABLE // Remove this and Class2 cannot be compiled, but OEDT doesnt even try to.
    :
END CLASS.
CLASS test.Class2  SERIALIZABLE
    INHERITS test.Class1: 
END CLASS.

**Comment by lneumeier** [comment]
Fixed in 9.4.0.
