### ISSUE TITLE
No support to switch between Visual Designer and code for User Controls

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#127]
When editing an ABL-Form, I can use F9 to switch between source and design.

This is not available for user controls (inheriting directly or indirectly from Progress.Windows.UserControl).
Please add this function.

PS: There are also ABL inherited controls (whatever that is) which could profit from that.

**Comment by lneumeier** [comment]
Verified.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.4.1.
