### ISSUE TITLE
No support for ENUMs

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#128]
Please add/correct support for ENUM in the following functions:
- Call Hierarchy: Where is the Enum or the Value name used.
- Rename one enum (No uses are refactored)
- Dependency compile 
  When changing an enum's value, only the ENUM source is compiled.
  When adding an enum, only the ENUM source is compiled.
  (Happens when one adds the enum after writing code that uses it and has an error there)

**Comment by lneumeier** [comment]
Fixed in OEDT 9.4.1.
