### ISSUE TITLE
View Design for extern Controls

### ISSUE THREAD

**Issue by MarcZ2202** [omecra/de.omecra.oedt.updatesite#129]
Hi,

switch to Design from context is only possible for Progress.Windows.Form.

We are using Telerik.WinControls.UI.RadForm or our derived Form xxControls.xxForm.

It is absolutely neccessary for us, to switch on this way (context or F9) to designview.

Thank you :-)

**Comment by MarcZ2202** [comment]
Maybe it is able to put a new fill-in to "Preferences - Oedt - Compile" named "Design Forms" where you can store den classnames

**Comment by mikefechner** [comment]
IMHO "absolutely necessary" is relative ... From the OEDT class editor, you can right click and "Open with" -> "OpenEdge Visual Desiner"

![image](https://user-images.githubusercontent.com/13220627/158795399-dbbffca4-3aad-4016-8b0e-006c847782b3.png)

But I agree a hotkey based access to the Visual Designer like in Forms would be nice to have.

**Comment by MarcZ2202** [comment]
Hello Mike,

I know this way, but it's just a workaround.
This is usually the way to set standardeditor for opening the file.

**Comment by lneumeier** [comment]
Should be fixed in OEDT 9.4.1.

**Comment by MarcZ2202** [comment]
Hi,

same issue with UserControls. Can you fix this too, please :-)

![image](https://user-images.githubusercontent.com/90957239/160084338-a3c1e7ff-02e7-42c9-adb6-024991374eb3.png)
