### ISSUE TITLE
False positive static variable and methods with output Temp-Table

### ISSUE THREAD

**Issue by MarcZ2202** [omecra/de.omecra.oedt.updatesite#130]
Hi,

not one, no two more things ;)

Using singletons:
![image](https://user-images.githubusercontent.com/90957239/158972352-7ac0344c-7ab2-42ea-9251-5d97e6a757ba.png)

![image](https://user-images.githubusercontent.com/90957239/158972504-cf378d6e-b92f-42b6-a74c-37366f5ac8b6.png)

L7Object.Adresse:FAdresse - marked as unused
FAdresse - not marked as unused

If the variable is specified once without the complete path, it works.

Methods with OUTPUT Temp-Table:

![image](https://user-images.githubusercontent.com/90957239/158972934-d070b2f9-b9d1-4b84-8149-17bb2e89f155.png)

![image](https://user-images.githubusercontent.com/90957239/158972990-c6f127bb-2bb1-4cd6-b269-f2ed79efbc9a.png)

**Comment by MarcZ2202** [comment]
Maybe another thing.

Using events or methods for subscribe events. I have to give the events parameters, but in 95% I never use this parameters.

![image](https://user-images.githubusercontent.com/90957239/158999608-34a081ff-f69f-4bde-8474-c253fb8cf0f7.png)

![image](https://user-images.githubusercontent.com/90957239/158999621-7bc528f6-79f9-4cf1-a295-be00a7405890.png)

**Comment by lneumeier** [comment]
`OUTPUT TABLE`should be fixed with 9.4.1.

**Comment by wiflc** [comment]
> Maybe another thing.
> 
> Using events or methods for subscribe events. I have to give the events parameters, but in 95% I never use this parameters.
> 
> ![image](https://user-images.githubusercontent.com/90957239/158999608-34a081ff-f69f-4bde-8474-c253fb8cf0f7.png)

This would be great if the warnings for event params can be hidden. Maybe it's possible to distinguish them by looking after @VisualDesigner.

**Comment by mikefechner** [comment]
Another solution might be a simple exclusion list by the parameter names in the OEDT settings. "sender" and "e" are typically not used elsewhere as parameter names. 

We typically remove the @VisualDesinger annotations from source code as they have no added value - and the VD dose not require them at all.

**Comment by lneumeier** [comment]
Fixed parameter evaluation in 9.4.2.

**Comment by lneumeier** [comment]
Qualified references to private static properties, variables or methods fixed (Refactoring & Unused members) in OEDT 9.4.3.
