### ISSUE TITLE
Caret position not correctly calculated when code is folded

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#131]
When a block is folded (I like to fold methods that are currently of no interest to me), then setting the caret to somewhere below it, will
- not correctly link to the method in the outline
- not recognize the identifier to be used with the "Rename" function

My guess is that the folded lines are not substracted from the line count.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.4.1.
