### ISSUE TITLE
Correct Keyword issue

### ISSUE THREAD

**Issue by MarcZ2202** [omecra/de.omecra.oedt.updatesite#132]
Hi,

I'm using the "Correct Keywords on save" option.

There is an issue with this option.

![image](https://user-images.githubusercontent.com/90957239/160086077-e786e3c4-a5c9-4006-8a3a-f2ffdc215e96.png)

![image](https://user-images.githubusercontent.com/90957239/160085964-3f5393ca-5683-4d52-9682-347c093bdaf1.png)

Correct is Center but on save it was changing so CENTERED.

**Comment by lneumeier** [comment]
Fixed with OEDT 9.4.2.
