### ISSUE TITLE
_msg not highlighted as a keyword

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#133]
I must admit, this is old and undocumented ... and not highlighted as a keyword in PDSOE too.

The _msg function returns the error message numbers similar to the ERROR-STATUS:GET-MESSAGE-NUM method. But it's widely used in legacy code (like the ADE source code).

```
FIND customer where custnum = -1 NO-ERROR .

MESSAGE _msg (1)
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
```

**Comment by lneumeier** [comment]
Added with OEDT 9.4.2.
