### ISSUE TITLE
Autcomplete EXCLUSIVE-LOCK

### ISSUE THREAD

**Issue by MarcZ2202** [omecra/de.omecra.oedt.updatesite#135]
Hi,

if I want autocomplete excl to EXCLUSIVE-LOCK I got...

![image](https://user-images.githubusercontent.com/90957239/161058265-b2f2d23c-a1c8-4983-8e31-0e0504649390.png)

![image](https://user-images.githubusercontent.com/90957239/161058285-44289d27-601b-4ba9-b8f0-71cd0567273a.png)

**Comment by lneumeier** [comment]
Fixed with OEDT 9.4.2.
