### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by MarcZ2202** [omecra/de.omecra.oedt.updatesite#136]
Hello,

since update to 9.4.2 the Developer Studio takes a very long time so save files.

Can anybody verify this?

**Comment by lneumeier** [comment]
I guess, that this is related to "Correct Keywords on save".

**Comment by MarcZ2202** [comment]
Hm, I don't think it took that much time before the update

**Comment by MarcZ2202** [comment]
https://user-images.githubusercontent.com/90957239/164156965-a031e48f-aa63-4bad-8c2d-ae70137f5234.mp4

**Comment by lneumeier** [comment]
I reverted the "Correct keywords on save" action to 9.4.1 and added some checks to fix #132
