### ISSUE TITLE
oeide_event not fired correctly

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#137]
When using OEDT the event "oeide_event" is only fired for some events but not for all of them.
I am missing get-focus, open-/close-file, before-/after-save.
The events before-/after-debug are replaced by before-/after-run when debugging as "Progress OpenEdge Application by OEDT".

I attach a _idestartup.p that traces the events in the default-window.
[_idestartup.zip](https://github.com/omecra/de.omecra.oedt.updatesite/files/8776817/_idestartup.zip)

**Comment by lneumeier** [comment]
Fixed in Oedt 9.4.4, except before-/after-run (this allows debugging 32bit applications from 64bit pdsoe)
