### ISSUE TITLE
Autocompletion ignores includeTooling

### ISSUE THREAD

**Issue by lneumeier** [omecra/de.omecra.oedt.updatesite#14]
Propathentries can be defined to be ignored by tooling:
`
<propathentry env="all" includeTooling="false" kind="src" path="@{ROOT}/internal" platform="All"/>
`
OEDT incorrectly offers classes from this propath in the autocompletion.
The default Progress Editor hides these classes as expected.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.0.0.

**Comment by pruefer90** [comment]
The new feature in OEDT 9.0.0 seems to hide the affected classes when typing a NEW statement only.
The objects are not hidden in a DEFINE VARIABLE statement or when accessing static methods.

**Comment by lneumeier** [comment]
Yes, that is true. Once your are using an "internal" class you get code assist.

**Comment by pruefer90** [comment]
The problem ist, that the first statement you write is DEFINE VARIABLE, at which point you are unaware that you see an internal class. Or you might see a large clutter of generated classes. Once you get to the NEW statement you get confused, that your class is missing.
The same is true for static methods. It is very likely, that you use an internal class unintentionally.

**Comment by lneumeier** [comment]
Just to sure
`DEFINE VARIABLE oSomeObject AS <CTRL+SPACE> gives you internal classes ?`
and
`InterClassFirstLetters <CTRL+SPACE> gives you internal classes?`

**Comment by pruefer90** [comment]
Exactly. I just noticed that I was mistaken and `NEW InterClassFirstLetters <CTRL+SPACE>` also gives me internal classes. I have used rebuild source project model.
This is an example propath entry:
`  <propathentry env="all" includeTooling="false" kind="src" path="@{ROOT}/dep/fio/src" platform="All"/>`

The Folder /dep/fio is a linked folder. The folder src contains source classes within further packages (altough it shows classes in the root package for me too).

**Comment by lneumeier** [comment]
Fixed in OEDT 9.0.1.

**Comment by pruefer90** [comment]
It seems to work fine now, thank you very much!
