### ISSUE TITLE
Dependency tree incorrect with conditionally nested includes

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#140]
It seems that the dependency information stored by OEDT does not keep track of wether an include is really used for a certain .W/.P.
Example:
Proc1.p
  {include.i}
Proc2.p
  &SCOPED NeedsInclude
  {include.i}
include.i
  &IF defined(NeedsInclude) NE 0 &THEN
  {DeepInclude.i}
  &ENDIF
If I make any changes to DeepInclude.i, both Proc2 (OK) and Proc1 (Not OK) are compiled by OEDT.

We found this because we made changes to one of our framework-includes, leading to 400+ files being compiled while only 25 should be.

**Comment by lneumeier** [comment]
OEDT does not evaluate preprocessor conditions. 

Apart from evaluating preprocessor conditions with another language (Java), OEDT have to parse and keep track of all occurrences of variables, includes etc. in order to do proper refactoring.

One side-effect is compiling more files then necessary.
