### ISSUE TITLE
Auto complete not working for tables prefixed with database alias

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#142]
When a table name is prefixed by a database alias instead of the logical name, auto complete is not recognizing the table and not showing any suggestions.
Database aliases should get detected from the list specified in the database settings:
![afbeelding](https://user-images.githubusercontent.com/8639525/185941460-52f76470-8440-474a-b1ae-c1d5bdde0560.png)

**Comment by lneumeier** [comment]
Fixed in 9.4.4.

**Comment by lneumeier** [comment]
Verified, it seems like I missed something.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.4.5.
