### ISSUE TITLE
False positive unused variable

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#146]
Perhaps not so common, but I found the following construct in our (legacy) code:

DEFINE VARIABLE Count AS INTEGER NO-UNDO.

DO WHILE NOT AVAILABLE Order Count = 1 TO 10:
    FIND Order WHERE ... .
    IF NOT AVAILABLE Order THEN PAUSE 1.
END.

The Count variable is incorrectly flagged as unused.

**Comment by lneumeier** [comment]
Behavior change in 9.4.4+, keywords as identifiers are now excluded for tasks like "Unused Variables".
