### ISSUE TITLE
Code completion on members of class defined in preprocessor

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#147]
This issue came up during conditional migration from our own List classes to the OpenEdge native list classes. Our strategy is to replace our self-made lists with Progress' List<T> classes based on the OpenEdge version.

Our idea is to change definitions of List variables and properties from 

```
DEFINE VARIABLE oTest AS Consultingwerk.OERA.ListTableModel NO-UNDO .
```

to 

```
&GLOBAL-DEFINE List-TableModel Consultingwerk.OERA.ListTableModel

/* ***************************  Main Block  *************************** */

DEFINE VARIABLE oTest AS {List-TableModel} NO-UNDO .
```

(the &GLOBAL-DEFINE will be conditional and in an include file based on PROVERSION).

And to my huge surprise, for the first time the PDSOE built in editor does more code-completion than OEDT ... :-)

**PDSOE:**

![image](https://user-images.githubusercontent.com/13220627/192004833-217fa002-6e6e-4f0f-b585-cf019ce815ea.png)
 
**OEDT:**

![image](https://user-images.githubusercontent.com/13220627/192004952-9654511c-d6c6-46e3-b056-3fafcd6e9755.png)

Can OEDT please be enhanced to support code completion for methods/properties/events when the variable or property definition is based on a preprocessor variable as shown above.

**Comment by LievenDeFoor** [comment]
@mikefechner perhaps a bit off topic, but does Progress provide interfaces for their collection classes? That way you could define your variables/parameters using the interface instead of specifying an actual implementation, and have your own collection classes implement the interface as well. Then just ensure no NEW statements are used to instantiate an object but instead use a factory (method).

**Comment by mikefechner** [comment]
@LievenDeFoor certainly off topic ;) - and unfortunately the answer is no - as the ABL does not allow us to implement generic types.

**Comment by LievenDeFoor** [comment]
> @mikefechner right, forgot about that tiny detail...

**Comment by lneumeier** [comment]
Added in 9.4.4.
