### ISSUE TITLE
Enhancement request: Add items from Progress outline to OEDT outline

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#149]
When using the Progress editor the outline has
* copy
* cut
* paste ???
* delete
functionality.

![image](https://user-images.githubusercontent.com/1312691/196137935-cd779da3-9d03-4fa3-8f9d-31e330d61c05.png)

These are missing from the OEDT outline. Some of our developers miss the delete functionality. 
Cut and copy seem useful to me as well.

It took me some time to figure out how paste works as it was disabled most of the time.
Paste only seems to work when you used copy or cut in the outline, it replaces the selected procedure with the one in the clipboard

Can these be added to OEDT ?

**Comment by lneumeier** [comment]
Added in OEDT 9.5.1.
