### ISSUE TITLE
Enhancement request: Add definitions and main block to appbuilder source outline

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#150]
The Progress editor has extra items for appbuilder blocks in the outline.

![image](https://user-images.githubusercontent.com/1312691/196141615-c5e93b98-89ab-47c6-8f16-e279c458ab18.png)

Can these be added to OEDT ? 
For us, this has a higher priority than #149

**Comment by lneumeier** [comment]
Added in 9.4.4.
![appbuilder-structure](https://user-images.githubusercontent.com/39283158/205495972-9c63982b-6477-4415-8dc5-1c8fabd04f91.PNG)
