### ISSUE TITLE
Correct keywords (from UPPERCASE to lowercase) writes "Class"

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#151]
When converting an ABL class file from UPPERCASE to lowercase the "Class" keyword is written in move case - both for the initial CLASS and the END CLASS.

**Comment by mikefechner** [comment]
The "Error" keyword on the 

`block-level on Error undo, throw.`

is also turned into mixed case. Are we coding Visual Basic? ;)

**Comment by lneumeier** [comment]
Fixed in 9.4.4.
