### ISSUE TITLE
Show more information in "Oedt Database" view

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#153]
The following extra info would be practical:
- Indication whether a field is mandatory
- Indication of unique index
- Indication of primary index
- Direction of index segments (ascending/descending)

**Comment by lneumeier** [comment]
I look into it.

**Comment by lneumeier** [comment]
> The following extra info would be practical:
> 
> * Indication whether a field is mandatory

Added in OEDT 9.4.5.

> * Indication of unique index
> * Indication of primary index
> * Direction of index segments (ascending/descending)

This is already available...
![database-view-properties](https://user-images.githubusercontent.com/39283158/218493212-a0a92e08-92f6-45b5-a4bf-b4c3105dfc05.PNG)

**Comment by LievenDeFoor** [comment]
I see the new "Mandatory" attribute but it shows "false" for all fields, no matter if they're mandatory or not...
Can you check?

**Comment by lneumeier** [comment]
Verified and fixed in OEDT 9.4.6.
