### ISSUE TITLE
Compact OEDT model databases?

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#154]
Hi,

For some reason my dev version OEDT model seems to have grown to over 25GB, while other workspaces for different versions (branched) of the same application are only a tenth of that.
The file <workspace>\.metadata\.plugins\de.omecra.oedt.core\<projectName>_sdb_941.data is currently at 25GB.
Is there a way to compact these files?
Or can they simply be deleted and be rebuilt, or will this break my workspace?

**Comment by LievenDeFoor** [comment]
I've tried removing <projectName>_sdb_941.* while Eclipse was closed and the database seemed to be recreated after reopening the workspace, so this action seems to be safe...

**Comment by LievenDeFoor** [comment]
The size increase seems to be a bug, see https://github.com/omecra/de.omecra.oedt.updatesite/issues/155

**Comment by lneumeier** [comment]
You can delete, when PDSOE is closed, delete all files for a <projectName>

.metadata.plugins\de.omecra.oedt.core\<projectName>
.metadata.plugins\de.omecra.oedt.core.assembly\<projectName>
.metadata.plugins\de.omecra.oedt.core.proclib\<projectName>
.metadata.plugins\de.omecra.oedt.core.project\<projectName>

On the next start of PDSOE and when the project is open, initialization starts automatically.
