### ISSUE TITLE
Source model database multiplies in size after each rebuild

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#155]
When doing a "Rebuild source model" the model database multiplies in size.
Tested by starting Eclipse, triggering a rebuild and closing Eclipse again.

**Comment by lneumeier** [comment]
I look into it.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.4.5. Database get's defragmented when it reaches 1.5 times the "normal" size.
