### ISSUE TITLE
Correct keywords w/uppercase camel-cases Error and Class

### ISSUE THREAD

**Issue by PeterJudgeZA** [omecra/de.omecra.oedt.updatesite#156]
Prefernces > OEDT > Editor  > Uppercase selected
Progress OpenEdge > Editor > Uppercase selected

The word "CLASS" is changed to "Class" in the `CLASS` and `END CLASS` statements.
The word "ERROR is changed to "Error" in any `ON ERROR` phrases.

Properties named `Server`, `Empty` and `Value` are uppercased.  These are both static and instance properties.

Using  OEDT 9.4.4

**Comment by lneumeier** [comment]
Hm, I thought I fixed this issue in OEDT 9.4.4 https://github.com/omecra/de.omecra.oedt.updatesite/issues/151 :-(

I look into it.

**Comment by lneumeier** [comment]
Verified and fixed in OEDT 9.4.5.
