### ISSUE TITLE
Issue with autocomplete

### ISSUE THREAD

**Issue by MarcZ2202** [omecra/de.omecra.oedt.updatesite#157]
Hi,

since the last update we've trouble with autocomplete.

**Comment by MarcZ2202** [comment]
![image](https://user-images.githubusercontent.com/90957239/219331950-f01d00e6-1e1c-46b5-b384-c7ea1cd4dd8b.png)

This is how it should be shown.

**Comment by lneumeier** [comment]
Have you already rebuild the assembly project?
