### ISSUE TITLE
Not recognizing all internal procedures?

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#158]
The attached source has 170 internal procedures, which are correctly shown in the standard OE Outline View.
But the OEDT Outline View shows only the first 161.

Why is that?
Is it a bug? 
I can't see anything weird in or after "suchRabattwerteUeberN2pos", which is the last shown procedure.

[kalkulieren.zip](https://github.com/omecra/de.omecra.oedt.updatesite/files/10793244/kalkulieren.zip)

**Comment by lneumeier** [comment]
I look into it.

**Comment by lneumeier** [comment]
Fixed in 9.4.5.
