### ISSUE TITLE
Correct Usings - Add missing USING statements

### ISSUE THREAD

**Issue by lneumeier** [omecra/de.omecra.oedt.updatesite#16]
In the standard OpenEdge editor you can use "Organize Usings" to add missing using statements. When there are multiple matches, OpenEdge presents a dialog to chose the correct one. The "Correct Usings" functionality in the OEDT editor does not have any of this functionality, it will not add any missing Using statements when doing CTRL-U.

**Comment by lneumeier** [comment]
Added in OEDT 9.5.2.

**Comment by LievenDeFoor** [comment]
While this seems like a nice feature, the dialog is shown for all duplicate matches, even those that are already "solved" (i.e. those that are already included in the USING statements).
The dialog should only be shown for types that have not been resolved yet.

**Comment by lneumeier** [comment]
Yes, you are right. This new "feature" revealed another bug. The check for existing using statements are not working.
I'll make a fix.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.5.3.
