### ISSUE TITLE
Feature request(s) - auto collapse USING statements and/or remember collapsed status

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#160]
Some of our sources contain a lot of USING statements.
Usually it's not important to see these so having them (optionally) collapsed by default could be useful.
Or alternatively it could be useful to remember, per file, what the collapsed state of code blocks is and restore that state upon file reopen.

**Comment by lneumeier** [comment]
Added in OEDT 9.4.7.
