### ISSUE TITLE
Enhancement request : matching bracket in OEDT editor functionality

### ISSUE THREAD

**Issue by ccecvb** [omecra/de.omecra.oedt.updatesite#161]
Progress editor has matching bracket functionality

## matching bracket indicator
![image](https://user-images.githubusercontent.com/74775499/230706638-a45578d4-214e-4c71-be16-417017730548.png)

## goto  bracket commando
![image](https://user-images.githubusercontent.com/74775499/230706768-6cf56c78-00ff-4c47-8ef0-9accdf7c7b2a.png)

can these be added to the OEDT editors

**Comment by lneumeier** [comment]
Fixed in OEDT 9.4.7.
