### ISSUE TITLE
Feature request - Show class/interface dependencies and depending classes/interfaces

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#162]
You can currently get the call hierarchy of a member of a class, but you can't quickly get:
- All classes/interfaces that implement/inherit a specific interface.
- All classes that (in)directly inherit a specific class.
- All classes/interfaces that depend on a specific class or interface.
- All classes/interfaces that a specific class/interface depends on.

I believe all this info is available in the source model, but some way to visualize this would be great.

**Comment by lneumeier** [comment]
Added Type-Hierarchy with super- and subtype modus.

**Comment by LievenDeFoor** [comment]
Hi Lars, I would like to come back to this one after our chat at the PUG.
You've provided Type hierarchy, starting from a specific type, and show the super types/interfaces it inherits/implements.
I think more is possible, in other directions as well (see list above).
Could you take another look at what might be easy (or less easy ;)) to implement?

**Comment by lneumeier** [comment]
Added Class-Dependency-View in OEDT 9.5.1 with referenced-by and depends-on modus.
