### ISSUE TITLE
Question: is OEDT compile using COMPILER:MULTI-COMPILE if set in _oeidecontext.p or _idestartup.p?

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#165]
Hi,

If I turn on COMPILER:MULTI-COMPILE by setting this in _oeidecontext.p or _idestartup.p, is this setting honoured and used by OEDT when compiling files or doing a clean + rebuild?

Thanks,
Lieven

**Comment by lneumeier** [comment]
Yes.
