### ISSUE TITLE
Outline doesn't show Methods with Input Parameters

### ISSUE THREAD

**Issue by wiflc** [omecra/de.omecra.oedt.updatesite#166]
Hi, 
I found a bug with oedt, where a method won't show up in the outline when there are input parameter types which start with a number.
My test class inside the directory 3a
```abl
USING Progress.Lang.*.
BLOCK-LEVEL ON ERROR UNDO, THROW.
CLASS 3a.test: 
END CLASS.
```
Class with test class as parameter in method
```abl
USING Progress.Lang.*.
BLOCK-LEVEL ON ERROR UNDO, THROW.
CLASS bbb: 
    CONSTRUCTOR PUBLIC bbb (  ):
    END CONSTRUCTOR.
    
    METHOD PUBLIC VOID method1(  ):
    END METHOD.    
    METHOD PUBLIC VOID ggg( INPUT test AS 3a.test ):
    END METHOD.
END CLASS.
```
The outline
![image](https://github.com/omecra/de.omecra.oedt.updatesite/assets/102349750/571779f2-8610-45ec-b7fb-001aeafb07bd)

**Comment by lneumeier** [comment]
Fixed with OEDT 9.4.8.
