### ISSUE TITLE
"Toggle Comment" keyboard problem with OE12.7

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#172]
Using Ctrl-Shift-7 to toggle a block comment always had an issue with leading spaces.

But with OE12.7 it doesnt work at all.
The corresponding menu item works like before (expecting the "/*" to not have spaces in front), but the keyboard shortcut does not work.
It may have to do with OE itself not recognizing Ctrl-Shift-7 as "Toggle Comment" but as "Toggle Line Comment" (Using // instead of /*).

PS: "Toggle Singleline Comment" has the same problem with leading spaces as "Toggle Comment"

**Comment by lneumeier** [comment]
Support for leading spaces added with OEDT 9.5.0. 

Regarding key-bindings, I'm sorry, I can't reproduce this error.
