### ISSUE TITLE
Code assist hints to wrong overload

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#173]
Hi,

I have 2 overloads of a method: one that takes a longchar and one that takes an object as input.
When calling the method with a character input, the longchar variant is used, but the code assist shows the object overload:

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/4be58986-26ca-4be8-92ab-cf4c09fec0fe)

This is on OEDT 9.4.8

**Comment by lneumeier** [comment]
Fixed with OEDT 9.5.0.
