### ISSUE TITLE
Call hierarchy for static method shows unrelated (but same named) invocations

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#174]
We have a public static Cleanup method in one of our classes.
When doing a "Open Call Hierarchy" the outline shows unrelated, but same named method invocations as well as the actual (single) call.
The other calls aren't even static, so they certainly don't belong in the list.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.5.1.
