### ISSUE TITLE
Dependency build no longer happening - how to debug/fix?

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#177]
Hi,

I have 1 project (in a separate workspace) where the dependency build is no longer happening (e.g. when changing an include file).
I've tried rebuilding the source object model to no avail.
"Build automatically" is turned on.
Any clues on how to fix this or find out what might be causing this?

Thanks,
Lieven

**Comment by lneumeier** [comment]
Hello,

Have you verified that the OEDT project builder is present in the .project file?
Does the "Include dependency view" show any dependencies?

**Comment by LievenDeFoor** [comment]
> Have you verified that the OEDT project builder is present in the .project file? 
This was the cause...
Might be something in our project setup script that broke this.
Thanks for pointing in the right direction!
