### ISSUE TITLE
Make new Java style comments optional

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#178]
Hi,

I'm not a fan of the new Java style comments that get used when using the "Toggle comment" functionality.
With the old style it was possible to uncomment parts of a commented block, by selecting it and using the Toggle comment shortcut again. 
Now this is no longer possible.
The new functionality also has problems to uncomment blocks that have nested comment blocks.
Could the new Java comments style be made optional?

Thanks,
Lieven

**Comment by LievenDeFoor** [comment]
Unless I'm mistaken you could previously select some words, tap the "toggle comment" shortcut and have it in between /* */ signs.
This is now no longer possible either...

**Comment by lneumeier** [comment]
> Unless I'm mistaken you could previously select some words, tap the "toggle comment" shortcut and have it in between /* */ signs. This is now no longer possible either...

I look into it.

**Comment by lneumeier** [comment]
> Hi,
> 
> I'm not a fan of the new Java style comments that get used when using the "Toggle comment" functionality. With the old style it was possible to uncomment parts of a commented block, by selecting it and using the Toggle comment shortcut again. Now this is no longer possible. The new functionality also has problems to uncomment blocks that have nested comment blocks. Could the new Java comments style be made optional?
> 
> Thanks, Lieven

Why do you not use the single-line comment style?
```
/* ... */
/* ... */ 
```
vs.
```
// ...
// ...
```

**Comment by lneumeier** [comment]
Fixed in OEDT 9.5.1.
