### ISSUE TITLE
Autocomplete not showing all properties/methods for certain .NET classes

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#180]
Hi,

When using the System.Windows.Forms.DataVisualization.Charting classes, some classes don't show all properties/methods in autocomplete.
Reopening the same file using the default Progress editor shows all expected items.
I have the issue in multiple workspaces and rebuilding the assembly model doesn't help.
`assemblies.xml` contains the correct entry:
`<assembly name="System.Windows.Forms.DataVisualization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>`
Compilation works so it's just a problem on the OEDT side I assume...

OEDT editor, only shows "Add" method, and nothing else:

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/f4ef4d78-3a65-41cd-afbd-e640de8f3c3e)

Progress editor, seems to show all properties/methods:

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/628a10e4-821a-4505-a6f0-2cb95cd4d026)

Any idea what might be causing this?

**Comment by lneumeier** [comment]
I look into it.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.5.1.
