### ISSUE TITLE
Installed 9.5.1 - Eclipse completely broken...

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#182]
Hi,

I just tried updating to the latest 9.5.1 release.
After restarting my Eclipse it seems it is totally broken:

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/84b27273-51ba-466b-aa3f-08a0a44c483a)

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/03f7d699-6c9f-440a-9b83-2131743287a0)

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/7c0eadc2-e862-4cd4-85c2-66779a789e75)

I was using Eclipse 4.13 with the OE plugins for 12.2 installed + OEDT 9.5.0 -> updated to 9.5.1
Any idea what could have broken everything, and how to fix it?

Regards,
Lieven

**Comment by LievenDeFoor** [comment]
I've restarted from scratch (eclipse-SDK-4.13-win32-x86_64.zip + plugins) and I'm back up and running...
Not clear what went wrong, but problem seems to be fixed.

**Comment by lneumeier** [comment]
It looks like that some plugins (com.openedge.project) couldn't be loaded. Is there a stacktrace in the log file?

**Comment by LievenDeFoor** [comment]
Closing as the problem seems solved by starting from a clean install...
