### ISSUE TITLE
Code completion uses wrong type (with same name)

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#184]
In my code I am using a "MarkerStyle" .NET enum, for which I have added a USING statement.
I also coincidentally have an ABL enum with the same name, used in the same source, but with the fully qualified name.
When I now request auto complete options for the .NET enum, I get a list of options from the ABL enum, which isn't even in scope at that place (since there is no using statement for it).

![afbeelding](https://github.com/omecra/de.omecra.oedt.updatesite/assets/8639525/f6f03625-6d71-4518-847b-0e3a71b3f968)

**Comment by lneumeier** [comment]
Fixed in OEDT 9.5.2.
