### ISSUE TITLE
Correct keywords updates procedure name

### ISSUE THREAD

**Issue by ccecvb** [omecra/de.omecra.oedt.updatesite#188]
As shown in the screenshot,
`PROCEDURE Init :` becomes `procedure initial :`

![image](https://github.com/omecra/de.omecra.oedt.updatesite/assets/74775499/69c2af18-54aa-4ab8-9872-2b82ee96547a)

Tested in oedt 9.5.3

**Comment by lneumeier** [comment]
Fixed in OEDT 9.5.4.
