### ISSUE TITLE
Please add Eclipse OEDT installation steps 

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#2]
On the , now closed, forum there was a post explaining how to install OpenEdge + OEDT as a regular eclipse download.
Can you supply that info somewhere, in the faq on the site or a a response here ?

**Comment by lneumeier** [comment]
I will add a HowTo section to the homepage, starting with this.

**Comment by lneumeier** [comment]
@cverbiest 

I added a HowTo section. Can you check the Howto wether I have missed something?
https://www.omecra.de/howto

**Comment by cverbiest** [comment]
Tested, result looks good thank you, 
Eclipse UI seems to be more responsive 
some remarks 

## Step 1: download
* Eclipse 4.8 is available, is that an option ? If know indicate maximum version of eclipse
* I used 4.7.3a

## Step 10 & 11
* Why look at timestamps, are they needed further on ?
* **copy** could be changed to **move** as they are deleted in step 13 anyway

## Steps 15 & 16
* copy with replace existing or skip ? I used replace

## Step 17
* why ? is this a backup or has it other uses (e.g. distributing to other users)

## Some more
* In the resulting eclipse the added update sites are no longer present, is this on purpose ?
* Could %DLC%/oeide/Architect_repo be used as update site after OE service pack install ?
* OEDT install itself is not included, probably on purpose

**Comment by lneumeier** [comment]
Carl, Thank you for your feedback and I will integrate your feedback.

Regarding Step 1:
Yes, PDSOE is unfortunately not compatible with Eclipse 4.8+.
https://community.progress.com/community_groups/openedge_development/f/19/t/39244

Regarding Step 17:
Yes, I use a zip archive to distribute it to other users. I'm doing this for 11.6.4 and 11.7.3, which are using the same Eclipse version, but for this article/HowTo I should shorten the process.

Regarding missing update sites:
Yes, this is something I haven't looked at it. The main issue is, that the configuration folder of the eclipse folder hold's lot's of information and sometimes specific information about the pc that eclipse was started, which could make the version incompatible for other users.

**Comment by lneumeier** [comment]
Update HowTo.
