### ISSUE TITLE
OEDT stuck at Parse Libraries for projects with no databases

### ISSUE THREAD

**Issue by lneumeier** [omecra/de.omecra.oedt.updatesite#25]
Quite often, I have a job that never finishes: That project does not have any database connections. When I add a databse and restart Eclipse, it works fine.

![](https://bitbucket.org/repo/kMed4oa/images/3776523673-parse.jpg)

**Comment by lneumeier** [comment]
Does this still happened in OEDT 8.4.4?

**Comment by pruefer90** [comment]
I have not encountered the issue in 8.4.4.
