### ISSUE TITLE
_oedtexporttables.p Database ****** has type oracle(869)

### ISSUE THREAD

**Issue by lievencardoen** [omecra/de.omecra.oedt.updatesite#3]
Does OEDT support Oracle?

I'm getting this error when opening a Project against Oracle database (Progress schema holder).

---------------------------
Error (Press HELP to view stack trace)
---------------------------
c:/workspace/eclipseworkspaceoe_11_7/.metadata/.plugins/com.openedge.pdt.core/.runtime/de.omecra.oedt.core.database/runtime/_oedtexporttables.p Database ***** has type oracle (869)
---------------------------
OK   Help   
---------------------------

Followed by:

---------------------------
Error (Press HELP to view stack trace)
---------------------------
But connection to type PROGRESS was requested. (916)
---------------------------
OK   Help   
---------------------------

If OEDT does not support Oracle, then how do I disable it for my Oracle projects?

Kind regards, Lieven Cardoen, MIPS

**Comment by lievencardoen** [comment]
I've edited the file _oedtdb.p.

```
PROCEDURE createOedtDatabases:

  DEFINE INPUT PARAMETER ip_cLocation AS CHARACTER NO-UNDO.

  DO iTemp = 1 TO NUM-DBS:

    IF DBTYPE(iTemp) = "PROGRESS":U
    THEN DO:

      fDBName = LDBNAME(iTemp).

      CREATE ALIAS VALUE(fAlias) FOR DATABASE VALUE(fDBName) NO-ERROR.
      RUN VALUE(fRunDir + "_oedtexporttables.p") (fDBName).

    END.

  END.

END PROCEDURE.
```

Could this be a fix?

Kind regards, Lieven Cardoen

**Comment by lievencardoen** [comment]
Hey Lars,

I'm more of a C# .NET guy. I can unpack the jar file, edit the  _oedtdb.p file, but then what? Can I just recreate a jar again? Isn't there an MD5 hash or something checking whether someone has tampered with the jar...

Kind regards, Lieven Cardoen

**Comment by lneumeier** [comment]
Hey Lieven,

A jar file is basically just a zip file. You can rename the file extension from jar to zip and extract _oedtdb.p, change and then add to the zip file again with any zip program, like 7-zip. After that, just rename the file extension back to jar.

**Comment by lievencardoen** [comment]
Ok, I tried that but eclipse seemed to have a problem loading the altered jar file. So I thought there was some kind of MD5 checksum check... I'll try it again. Thx.

**Comment by lneumeier** [comment]
What OpenEdge Version are you using, 11.7.x?

**Comment by lievencardoen** [comment]
Currently 11.7.2 with a unofficial hotfix. But next week probably going to install 11.7.3.

**Comment by lneumeier** [comment]
I updated the corresponding jar file (rename file extension from zip to jar - jar files can not be uploaded in GitHub comments). Please copy & override the jar in %PDSOE-Location%/plugins and start PDSOE with the -clean option.
[de.omecra.oedt.core.database_8.4.3.zip](https://github.com/omecra/de.omecra.oedt.updatesite/files/2349948/de.omecra.oedt.core.database_8.4.3.zip)

**Comment by lievencardoen** [comment]
Thx! Will try it Thursday!
