### ISSUE TITLE
OEDTdoc incompatible with ABLDoc

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#31]
OEDTdoc looks like this:
```
/**
 * Purpose:
 * Notes:
 *
 * @param param1
 * @param param2
 * @return return value
 */
```
ABLDoc looks like:
```
/*
    Purpose:
    Notes:

    @param param1
    @param param2
    @return return value
*/
```
Note the main difference: no leading * in ABLDoc.
These leading * seem to prevent the correct generation of ABLDoc files (Purpose and Notes are not picked up)

Ideally Progress should just support this, but for now an option to omit the leading * would be a workaround...

**Comment by lneumeier** [comment]
Progress ABLDoc supports parsing of "Java-Doc-Style" comments.

Here is a whitepaper:
https://community.progress.com/cfs-file/__key/telligent-evolution-components-attachments/13-137-00-00-00-00-19-57/Supporting_5F00_JavaStyleComments_5F00_in_5F00_ABLDoc.pdf?forcedownload=true

**Comment by LievenDeFoor** [comment]
Thanks Lars, I'll look into it.

**Comment by lneumeier** [comment]
Okay, I will look into it.

KB-Article:
https://knowledgebase.progress.com/articles/Article/How-to-make-abldoc-compatible-with-javadoc-style-comments

**Comment by LievenDeFoor** [comment]
Thanks.
Yes, the KB article was added after my inquiry with tech support ;-)

**Comment by lneumeier** [comment]
> That seems to work, although Purpose: and Notes: are now on a single line...
> 
> Perhaps you should add a `<br/>` by default to make it look like before?

This is not possible, the ABLDoc JavaCommentParser eliminates this. I will add a new ABLDoc-Tagparser that converts OedtDoc in a Progress Comment and then calls the ABLDoc-Progress-Parser.

**Comment by lneumeier** [comment]
Fixed with OEDT 8.4.6

**Comment by LievenDeFoor** [comment]
Do I have to revert to the original ABLDoc parser instead of the one mentioned in the whitepaper/KB article? Because I'm not seeing any difference currently...

**Comment by lneumeier** [comment]
Yes, that right. The Templates in the abldoc.core plugin and the property file in abldoc.ui have to be reverted to the default ones.
