### ISSUE TITLE
Unused variable "Count" false positive

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#32]
Defining and using a variable named "Count" is falsely detected as unused.

DEFINE VARIABLE Count AS INTEGER NO-UNDO.
ASSIGN Count = NUM-ENTRIES(SomeString).

**Comment by lneumeier** [comment]
Verified, I look into it.

**Comment by lneumeier** [comment]
Fixed with OEDT 8.4.7.
