### ISSUE TITLE
Automatically check syntax not working since 8.4.4

### ISSUE THREAD

**Issue by pruefer90** [omecra/de.omecra.oedt.updatesite#36]
Ever since upgrading OEDT from 8.4.3 to 8.4.4 (and 8.4.7) automatically check syntax is not working anymore. The option is turned on, but compile errors only appear after saving a file.

**Comment by lneumeier** [comment]
Verified, I will look into it.

**Comment by lneumeier** [comment]
I found the problem. Will be fixed with OEDT 8.4.8

**Comment by lneumeier** [comment]
Fixed with OEDT 8.4.8.
