### ISSUE TITLE
OEDT facet versions don't match installed oedt version

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#37]
OEDT version is 8.4.7
Facet is 8.7

These 2 don't match. 
I suppose 8.7 is the facet version for 8.4.7 but I'd like to be sure this is correct

Secondary question
Would it be possible to have the facet version limited to 8, similar to the OpenEdge facet where 11 covers all 11.x releases ? 
This would reduce the number of updates to the project definitions

**Comment by lneumeier** [comment]
Currently OEDT is using the facet version to cleanup old OEDT temp files in %workspace%\.metadata\plugins\de.omecra.* directories.

**Comment by lneumeier** [comment]
> Secondary question
> Would it be possible to have the facet version limited to 8, similar to the OpenEdge facet where 11 covers all 11.x releases ?
> This would reduce the number of updates to the project definitions

Can you describe the problem? OEDT is automatically updating the facet version and cleans up old files.

**Comment by cverbiest** [comment]
We have our project definition under version control.
Not all developers are always on the same version of OEDT 
Different versions of OEDT will cause update conflicts on the project definition

**Comment by lneumeier** [comment]
Okay, I will implement another solution for cleaning up old files in the workspace metadata directory, but this can not be fixed before OEDT 9 get's released.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.0.0.
