### ISSUE TITLE
save include in OEDT include editor results in compile of include

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#38]
save include in OEDT include editor results in compile of include

Console shows
[14-01-2019 14:12:36] Compilation failed for /appl/src/erpscan/rfcallw.i

Build settings does not in include .i as compilable

![image](https://user-images.githubusercontent.com/1312691/51115013-4ef49400-1807-11e9-9dc6-c41ff4626f8a.png)

I'm not sure where to look for this issue
Save the same include file using Progress include editor does not show this behaviour.

**Comment by lneumeier** [comment]
Which OEDT version are you using? Can you post a screenshot of
Window -> Preferences -> Oedt ?

**Comment by cverbiest** [comment]
Using 
  Oedt Feature	8.4.7	de.omecra.oedt.feature.group	Omecra UG (haftungsbeschränkt)

In the same environment I notice that compile is not started for a .w .

OEDT settings 
![image](https://user-images.githubusercontent.com/1312691/51116167-a34d4300-180a-11e9-960c-fdfb90e6cbc3.png)

![image](https://user-images.githubusercontent.com/1312691/51116230-d4c60e80-180a-11e9-9374-104e9a8cff9d.png)

**Comment by lneumeier** [comment]
Verified and I found the issue. OEDT 8.4.8 will fix this issue (released later today).

**Comment by cverbiest** [comment]
Ok, thanks,
FYI I just noticed that once I launch something a build does start

**Comment by lneumeier** [comment]
You can uncheck "General options" - Build (if required) before launchung
Window -> Preferences -> Run/Debug -> Launching

**Comment by lneumeier** [comment]
@cverbiest 

From looking at your preferences, I highly recommend to activate "Build Automatically" and active "Disable Compile for Auto-Build" if you do not want compilation of your source files but at least for the files that are opened in an OEDT Editor.

https://github.com/omecra/de.omecra.oedt.updatesite/releases/tag/v8.4.8

**Comment by lneumeier** [comment]
Fixed with OEDT 8.4.8.
