### ISSUE TITLE
Export/import preferences / where are preferences stored

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#39]
Hi,

Could you tell where the preferences are stored? Are these per Eclipse installation or per workspace? Can an export/import option be provided?

Regards,
Lieven

**Comment by lneumeier** [comment]
The preferences are stored under
%workspace-location%\.metadata\.plugins\org.eclipse.core.runtime\.settings\de.omecra.oedt.ui.prefs

**Comment by lneumeier** [comment]
Right-Click on the Navigator View -> Export -> Export ... -> General -> Preferences exports all preferences by default.

OEDT 8.5.0 supports the possibility to export the Oedt Preferences separately.
![preferences](https://user-images.githubusercontent.com/39283158/51703160-f054c480-2015-11e9-9d90-338026502a63.png)
