### ISSUE TITLE
Flag non-void methods/functions without return statement

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#4]
I don't know how feasible this is, but as it's one of the top requested features at the OpenEdge enhancements forum (https://community.progress.com/community_groups/products_enhancements/i/openedge/compiler_should_prevent_methodsfunctions_without_return_statement) I would like to add this here.

Detecting no return statement (preferably in all possible exit paths) would be a great addition to the plugin...

**Comment by lneumeier** [comment]
Obsolete, implemented by the OpenEdge Compiler.
