### ISSUE TITLE
Valid source fails to compile with OEDT

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#40]
Same source, same environment
OEDT show compilation errors
OpenEdge editor shows syntax ok

![image](https://user-images.githubusercontent.com/1312691/51377780-03dec780-1b0c-11e9-8419-d67ec8f1d5e5.png)

![image](https://user-images.githubusercontent.com/1312691/51377798-0fca8980-1b0c-11e9-8f4a-2f9293e9b209.png)

**Comment by cverbiest** [comment]
checked project facet & builder properties, they look ok

**Comment by lneumeier** [comment]
This is strange, because "Check Syntax" is calling PDSOE functionality. There is no real custom OEDT code.

What Openedge version are you using?

**Comment by cverbiest** [comment]
Openedge 11.7.4, eclipse environment constructed using steps on omecra site.
Error occurs with the bufferhandle::fieldname syntax

**Comment by lneumeier** [comment]
Do you use "Automatically Check Syntax" or have your pressed CTRL+SHIFT+C "Check Syntax"?

**Comment by lneumeier** [comment]
> Updated OEDT to 8.4.8, same result,

Is this the only file or do you get these kind of errors on different files too?

**Comment by cverbiest** [comment]
I've never seen this behaviour before but I also get the issue if I copy that code into a new class
```
class OedtTestCase40:


    method public void Test(  ):

        define variable lUserInfo   as character no-undo initial "unknown".
        define variable lUserId     as character no-undo initial ?.
        define variable lTimeString as character no-undo.

        define variable hDbBuffer   as handle    no-undo.
        lUserId = hDbBuffer::​CCESF-LASTSAVE-XU-N.
        lTimeString = string(hDbBuffer::​CCESF-LASTSAVE-DTZ).

    end method.

end class.
```
