### ISSUE TITLE
"null        " inserted in macro/template string when pressing return

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#41]
I have a macro/template (Preferences > Progress OpenEdge > Editor > Templates) configured as follows:
stripe -> /* --------------------------------------------------------------------- */

When I now type "stripe" and hit space bar, everything works as expected, and the comment line is inserted as above.
When I type "stripe" and hit return/enter, I get the following:
/* ---null        ------------------------------------------------------------------ */

**Comment by lneumeier** [comment]
Fixed with OEDT 8.5.0.
