### ISSUE TITLE
Autocompletion not working for temp-tables with nested preprocessor suffix

### ISSUE THREAD

**Issue by pruefer90** [omecra/de.omecra.oedt.updatesite#43]
We have the following file structure:
File tttest.i:
```
DEFINE TEMP-TABLE ttTest{1} NO-UNDO
  FIELD myField AS CHARACTER.
```
File dstest.i:
```
{tttest.i {1}}
DEFINE DATASET dstest{1} FOR ttTest{1}.
```
File test.p:
```
{dstest.i}
{dstest.i suf}

CREATE ttTest.
ttTest.myField = "c". //Autocompletion not working
```

The preprocessor allows us to define the dataset and tt twice with different suffixes. Autocompletion with suffixes works fine for the dataset, however the nested tt shows up as ttTest{1} and autocompletion does not work when referencing the table just as ttTest.

**Comment by lneumeier** [comment]
Verified and fixed in OEDT 8.5
