### ISSUE TITLE
OEDT should not scan derived files

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#44]
I'm starting to use PCT Compile on eclipse workspaces or vice versa use eclipse as debugger on a workspace that resulted form a PCT build.

In those cases a .pct directory with xref, logfiles, preprocess files etc. exists in the project.

I noticed OEDT starts scanning those files.
I marked the .pct directory as derived but that did not help.

![image](https://user-images.githubusercontent.com/1312691/52629465-0558a100-2eba-11e9-8220-867aea0d7cb7.png)

**Comment by pruefer90** [comment]
We use the derived attribute for generated sources. Those files are in our propath and must definitely be scanned in our project.
Are your temporary files in the project propath?

**Comment by lneumeier** [comment]
Okay, so it must be optional. 

@cverbiest 
I assume you don't want to open these files in an editor?

**Comment by cverbiest** [comment]
Yes, the project root is in the propath and .pct is in the project root.
I could try to remove that from the project definition but that will not always be simple.

If derived files are considered sources by OEDT, would it be possible to add an exclude pattern where we could add .pct

I'm trying to get towards a seamless integration between

- PSDOE
- OEDT
- PCT, for doing overnight builds on an eclipse workspace
- Sonarlint

**Comment by cverbiest** [comment]
@lneumeier normally we would not open them in an editor of course there are times when we do want to look into the listings but any editor will do then

**Comment by pruefer90** [comment]
Have you considered adding your sources to a src folder and only adding that folder to the propath?

**Comment by cverbiest** [comment]
@pruefer90 our sources are in an src directory.
We have the project root in the propath

- because Progress adds it by default, probably a lame excuse but I'm not sure what OE tools expect project root in propath
- I think Appbuilder needs it, but I'll test without
- some projects such a Consultingwerk SmartComponents don't (strictly) use the src

I'll try to get rid of projectroot in the propath

**Comment by lneumeier** [comment]
Added an option to skip derived files.
