### ISSUE TITLE
Run/Debug As > Progress ABLUnit Application not available from OEDT Class Editor context menu

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#45]
When opening a Test class (class containing at least one method annotated with the @Test. annotation) in the standard OpenEdge ABL editor, the Run/Debug As context menu contains both "Progress OpenEdge Application" and "Progress ABLUnit Application".
When doing this from the OEDT Class editor, only the "Progress OpenEdge Application" option is available.

**Comment by lneumeier** [comment]
Yes, this is a know issue. The context entry is bind to the Progress ABL editor. I will look again into it.

As a workaround, link the project explorer to the editor and choose from the project explorer "Progress ABLUnit Application"

**Comment by lneumeier** [comment]
Fixed in OEDT 9.0.0.
