### ISSUE TITLE
Switch AppBuilder (question)

### ISSUE THREAD

**Issue by KevinHermansR** [omecra/de.omecra.oedt.updatesite#47]
When you are in the "ABL UI Designer" and you press F9 it opens "Openedge ABL editor"
In the "OpenEdge ABL editor" if you press "shift+F9" it opens "ABL UI Designer".

Want to replace it in keys but no success is there a way to change this?
At this moment I tried to configure it like in the print screen.

![image](https://user-images.githubusercontent.com/47971737/53327971-3fc63300-38e9-11e9-8053-9d68943058a9.png)

Kind regards,
Kevin Hermans

**Comment by lneumeier** [comment]
I can add SHIFT+F9 to open ABL UI Designer/Visual Designer, but F9 from the Visual Designer/ABL UI Designer seems to be hardcoded...

**Comment by KevinHermansR** [comment]
Indeed it will still be an added value so it will be appreciated.
And for the hardcoded part it is like it is.

**Comment by lneumeier** [comment]
Fixed in OEDT 9.0.0.
