### ISSUE TITLE
Macro/template expansion with multiple placeholders broken in 8.5.0

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#48]
Macro/template like the following no longer expands correctly:
`DEFINE VARIABLE ${Name} AS ${DataType} NO-UNDO.`
Only the first placeholder can be entered.
This is quite vital functionality for us...

**Comment by lneumeier** [comment]
Verified, I look into it.

**Comment by lneumeier** [comment]
Fixed in OEDT 8.5.1 and OEDT 9.0.0.
