### ISSUE TITLE
Autocomplete broken?

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#57]
I'm not sure if this is related with 9.0.x but I no longer get any auto completion for types in my project. I still get completion proposals when using types from other projects/pl's inside my project.
I've checked both the Build > Source tab in project properties and tried rebuilding the source project model, but to no avail... Any other suggestions or is this a bug?

**Comment by LievenDeFoor** [comment]
I have tried deleting the oedt files from .metadata\plugins as well, but to no avail...

**Comment by LievenDeFoor** [comment]
OK, found it. Exclude from OpenEdge tooling was checked for my projects folders.
Could it be that this was not used in the past? Either way, it's fixed now...

**Comment by lneumeier** [comment]
Yes, OEDT 9.0.1 recognizes includeToolingFalse  - see #14
