### ISSUE TITLE
How handle update Oedt config file

### ISSUE THREAD

**Issue by KevinHermansR** [omecra/de.omecra.oedt.updatesite#58]
I have a question what's the best way for updating Oedt.
Because in the file org.eclipse.wst.common.project.facet.core.xml there is next line
<installed facet="de.omecra.oedt.ui.facet" version="9.0"/>

This file is updated every time we update Oedt it's hard to maintain or maybe I'm doing it wrong.
1) Update Oedt
2) Commit and push the change of the config file (On all projects)
3) Merge this change to all our branches (Many)
4) All developers need an upgrade (normal)
5) All developers get a conflict and may take their or the origin version. Also not a great situation.

This is somewhat time consuming and not the purpose I think. And we need that file in git if we start or project so PDS know which facets the project needs.
I was thinking to write a little script that does this automatically but first I want to hear what's your thought about the problem.

**Comment by lneumeier** [comment]
I'm personally not a fan of tracking this file with git or any other scm. The .settings folder which contains the org.eclipse.wst.common.project.facet.core.xml file is hidden under linux and macOS and I think that could be an indicator, that the content of this folder should not be tracked...

If a plugin with a facet get's installed/activated or updated and therefore change the facet version, it often reflect a change in the eclipse installation and/or the workspace (.metadata folder). 

Forcing a different(newer) facet version through a scm checkout and not through the responsible plugin eliminates the part a plugin would do when updating the facet version.
(there is an eclipse extension point, to register a class when a facet version needs to be updated).

However, starting with OEDT 9 the facet version (9.0) will no longer change for the same major version.

**Comment by KevinHermansR** [comment]
But what you do with a new install at this moment I import a config file that load around 20 projects(after all plugins are installed) .
These 20 projects automatically have there facets but if it's not in your scm what do you do in this situation?

The solution that all major versions doesn't update in the facets is great because know it was 8.6, 8.7 and we were waiting on a solution for this. So for me this question is solved.

Thank you
