### ISSUE TITLE
Format code

### ISSUE THREAD

**Issue by lcouso** [omecra/de.omecra.oedt.updatesite#59]
The standard OpenEdge editor allows to format the code.
Either the selected code or the whole file.

Is it possible to add that feature to the OEDT editor ?
Ideally it should follow the same rules as those of the OpenEdge editor.

**Comment by Ton-Pe** [comment]
Vote for this. Especially we would need "Correct indentation" functionality.

**Comment by lneumeier** [comment]
Added in 9.3.6.
