### ISSUE TITLE
Private method incorrectly flagged unused

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#6]
Private members of a class are "class private" in ABL (vs "object/instance private").
This means a Class "Person" can e.g. have a private method "ShowPrivate" that is accessible from outside the instance in this case:

    CLASS Person:

        DEFINE PRIVATE VARIABLE Name AS CHARACTER NO-UNDO.
        DEFINE PRIVATE VARIABLE Mother AS Person NO-UNDO.

        METHOD PUBLIC VOID CreateMother(Name AS CHARACTER):

            Mother = NEW Person().
            Mother:Name = Name. /* Works even though this is private! */

        END METHOD.

        METHOD PUBLIC VOID ShowMotherName():

            MESSAGE Mother:Name
                VIEW-AS ALERT-BOX.

            Mother:ShowPrivate(). /* Works even though this is private! */

        END METHOD. 

        METHOD PRIVATE VOID ShowPrivate():

            MESSAGE "Private!"
                VIEW-AS ALERT-BOX.

        END METHOD.

    END CLASS.

The ShowPrivate() method is incorrectly flagged as unused.
No warning is shown for the Name variable though...

**Comment by lneumeier** [comment]
I look into it.

**Comment by LievenDeFoor** [comment]
This doesn't appear to be fixed with version 9.
Any update on what version this will be fixed in?

**Comment by lneumeier** [comment]
It is targeted for 9.4.

**Comment by lneumeier** [comment]
Fixed in 9.2.4.
