### ISSUE TITLE
Version 9.0.2 fails to install due to missing dependency

### ISSUE THREAD

**Issue by lcouso** [omecra/de.omecra.oedt.updatesite#60]
Version 9.0.2 fails to install with error :
```
Missing requirement: Oedt Feature 9.0.2 (de.omecra.oedt.feature.group 9.0.2) requires 'com.openedge.pdt.debug.core 11.7.4' but it could not be found
```

Version 9.01 installed fine.

The "version" file of the dlc indicates : "OpenEdge Release 11.7.2 as of Tue Oct 24 19:02:00 EDT 2017".

Is it possible to remove that dependency ?
The dlc is managed in a company wide fashion and I'm not sure if I'll be able to upgrade it in a timely manner.

Thank you.

**Comment by lneumeier** [comment]
Fixed with OEDT 9.0.3
