### ISSUE TITLE
Unrecognized ERROR-OBJECT keyword

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#64]
Asynchronous request object handle has a (new?) property ERROR-OBJECT.
This can contain the error that was returned/thrown from an asynchronous request.
It appears this keyword is not recognized by the OEDT editor (not cased correctly, not colored)

**Comment by lneumeier** [comment]
I look into it.

**Comment by lneumeier** [comment]
Fixed in 9.1.0
