### ISSUE TITLE
Copy results of include dependencies to clipboard

### ISSUE THREAD

**Issue by Ton-Pe** [omecra/de.omecra.oedt.updatesite#65]
Open include dependencies is a great feature. Please add possibility to copy names of selected files from Oedt Include Dependencies view to clipboard. Copied name should be relative to propath. 

Example: Oedt Include dependencies shows as a result for _prog/salesorder/common.i_:
- prog/salesorder/common.i
-- prog/salesorder/page.w
-- prog/salesorder/page2.w

User will select those .w lines and copies to clipboard (context menu function if possible). When user pastes data from clipboard, the result should be:
```
prog/salesorder/page.w
prog/salesorder/page2.w
```

**Comment by lneumeier** [comment]
I look into it. (9.1 or 9.2)

**Comment by lneumeier** [comment]
Added in 9.1.2.

**Comment by Ton-Pe** [comment]
I can confirm this works like expected. Thank you very much!
