### ISSUE TITLE
Enhancement request: Add option/toggle for xml xref

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#67]
The OEDT xref compile produces only legacy flat file xref.
Could you add option to produce XML xref.

This could be

- a check box in the configuration

- an extra command xml xref in the compile menu

either would work for me.

**Comment by lneumeier** [comment]
I will implement an extra command.

**Comment by lneumeier** [comment]
Added in OEDT 9.1.2.
