### ISSUE TITLE
Oedt compare viewer ignore casing

### ISSUE THREAD

**Issue by KevinHermansR** [omecra/de.omecra.oedt.updatesite#68]
Is it possible to add an option to ignore casing in the Oedt compare viewer

![image](https://user-images.githubusercontent.com/47971737/59756407-f0d24e00-9289-11e9-8eef-e920553b65f7.png)

**Comment by lneumeier** [comment]
I look into it.

**Comment by lneumeier** [comment]
Unfortunately there is no option in the eclipse compare framework to ignore casing. So, nothing I can activate. :-(
