### ISSUE TITLE
rename refactoring should be conditional

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#7]
In our projects I had 2 products.i files.
One is earlier in the propath than the other.

I renamed the first to products.i.old so that the project would start using the second version of products.i
Unfortunately all sources using products.i got refactored automatically to now use products.i.old

Please make this kind of refactoring conditional

**Comment by lneumeier** [comment]
Sounds good.

**Comment by lneumeier** [comment]
Moved to 9.4.0, because there is a workaround and other items are more important.
