### ISSUE TITLE
Enhancement request: Compile missing files menu option

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#70]
There currently are two OEDT compile options on a project.

* Compile Error files
* Compile files

Is it possible to a a third option `Compile missing files ` ?
This would only compile those files for which there is no rcode.

I frequently delete rcode for various reasons, using various criteria 

- all
- according to file age
- following certain name patterns
- ...

This option would be usefull to compile only the ones that are missing.

**Comment by lneumeier** [comment]
Yes, this is possible.

**Comment by lneumeier** [comment]
Added in 9.2.2
