### ISSUE TITLE
enhancement request: collect/show database info only once

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#72]
We have multiple projects using the same databases.
This information is collected and shown per project.
It would be nice if there was an option to have the information for a database only once.

![image](https://user-images.githubusercontent.com/1312691/62199958-bbd71200-b384-11e9-8858-02a89a62d88a.png)

search shows the result for each project, but they are all the same
![image](https://user-images.githubusercontent.com/1312691/62200665-2e94bd00-b386-11e9-9de9-867acfefebe9.png)

I think that the information is also gathered and stored mulitple times, resulting in a very large .metadata\.plugins\de.omecra.oedt.core directory

![image](https://user-images.githubusercontent.com/1312691/62200517-e5dd0400-b385-11e9-97a7-ef8d1eec411a.png)

**Comment by lneumeier** [comment]
There is already a filter for 'project'. 

At the moment OEDT is storing only the schema and logical database name, not the database location, which would be necessary to identify, whether the same database is used in more than one project.
Many customers are using multiple projects with the same logical database name, but with different schemas (added/removed some tables/fields). In that case, there is no optimization possible.

Databases are stored in de.omecra.oedt.core.database and not in de.omecra.oedt.core.
