### ISSUE TITLE
enhancement request: go to source line

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#74]
This is a feature that exists in the OpenEdge editor but is missing from oedt.

It allows you to enter the line number as show in a stack trace and position on the corresponding line in the source.

![image](https://user-images.githubusercontent.com/1312691/62611214-6f9c4c80-b905-11e9-918e-c50634104d59.png)

**Comment by lneumeier** [comment]
Sounds good. I look into it.

**Comment by lneumeier** [comment]
Added in 9.3.0.
