### ISSUE TITLE
Code completion for :HANDLE

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#81]
When I have a method which expects an HANDLE parameter I'd like to have code completion on 

objRef:MethodName (BUFFER eCustomer:

Following the Colon, it would be cool, if HANDLE would be provided as the (FIRST) option.

Similar with DATASET dsCustomer:

**Comment by lneumeier** [comment]
I enhanced to code assist proposals to show buffer, temptable and datasets as arguments completion, which automatically inserts 
```
objRef:MethodNa<CodeAssist> -> "Proposals Dialogs" - choose eCustomer
result:
objRef:MethodName(BUFFER eCustomer:HANDLE).
```

**Comment by lneumeier** [comment]
Added in 9.2.6
