### ISSUE TITLE
Issue with BUFFER-NAME completion for HANDLE parameter

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#82]
I have just upgraded to 9.2.6 ... 

And it looks like there's an issue with the above new (cool) feature. It seems to paste a buffer's Before-Buffer name, not the actual buffer.

Here's a video of the issue:

[2019-12-01_20h38_21.zip](https://github.com/omecra/de.omecra.oedt.updatesite/files/3908642/2019-12-01_20h38_21.zip)

In the end, the code completion drop down should offer both the buffer and the Before-buffer name.

**Comment by lneumeier** [comment]
Fixed in 9.2.7.

**Comment by mikefechner** [comment]
Works. Thanks for the quick fix!
