### ISSUE TITLE
@TempTable annotation does not show on code completion + missing documentation

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#83]
https://www.omecra.de/features describes the temptable annotation but it does not show an example of what the annotation looks like.

None of the popup menus or autocompletion options show the "add @Temptable annotation" option
![image](https://user-images.githubusercontent.com/1312691/70987504-529c3500-20c0-11ea-8193-fa7ad3912775.png)

Is there a description of the available annotations and their syntax

**Comment by lneumeier** [comment]
Can you try this:

1. Move the cursor into the statement (in this example htest)
2. Press CTRL+1 (Quick Fix/Assist)

You should see a popup with
"add table annotation and add temptable annotation"

**Comment by lneumeier** [comment]
Added CTRL + 1 to the documentation.
