### ISSUE TITLE
Eclipse crash when building assembly model

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#85]
Hi Lars,

I vaguely remember reporting the same issue in the past, but can't seem to find any reference to it...
After buying several licences, my colleagues are starting to install OEDT onto their existing installations and some are seeing issues.

On initial build of the assembly model (and subsequent manual retries) Eclipse crashes.
I'm attaching the .log file.

Can you take a look?
At the moment this is preventing the roll-out to other colleagues as well.

Regards,
Lieven
[version](https://user-images.githubusercontent.com/8639525/76423044-7bbe2000-63a6-11ea-8908-66e3c25f3242.png)
[eclipse.log](https://github.com/omecra/de.omecra.oedt.updatesite/files/4318543/eclipse.log)

**Comment by lneumeier** [comment]
Hello Lieven,

Did your colleagues get a java runtime exit message? If that's the case, please change the "vm" parameter in the eclipse.ini (default PDSOE location: %DLC%/oeide/eclipse/eclipse.ini)
```
from:
-vm
%DLC%/jre/bin/javaw.exe
to
-vm
%DLC%/jre/bin/server/jvm.dll
```

**Comment by LievenDeFoor** [comment]
Hi Lars,

At least one of them did, so we'll try out your suggestion.

I'll let you know how it goes...

**Comment by LievenDeFoor** [comment]
Problem seems solved by your workaround + increasing -xms to 256 and -xmx to 1024.
Could you tell again why the jvm.dll is a working workaround?

**Comment by lneumeier** [comment]
This issue is related to how assemblies are loaded into the jvm through PDSOE. If your are using **lot's** of assemblies this error can be observed through the class browser or by creating a new .net form in a plain PDSOE.

I created a case with Progress 4 years ago when this error got introduced in 11.6.1.
This was my feedback on the case:
```
ErrorLog Eclipse:
- SWTError: NO more handles and the view is empty

Setting Xmx to 512m fixed this problem.

But the best solution would be to changed simply:
-vm
D:\Progress\dlc116/jre/bin/javaw.exe
to
-vm
D:/Progress/dlc116/jre/bin/client/jvm.dll

After that it even works for Xmx1024m.

But I think, that the developers should look into oeacb.dll for memory leaks.
```

**Comment by LievenDeFoor** [comment]
Problems seem solved, thanks
