### ISSUE TITLE
Single line comment color

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#86]
Hi,

Do you know where you can change the color for single line (//) comments?
These don't seem to follow the comments color and I can't seem to find where I can change this.

**Comment by lneumeier** [comment]
Multi-Line Comments and Single-Line Comments have the same color in OEDT.
![oedt-colors](https://user-images.githubusercontent.com/39283158/76659409-a6f76980-6576-11ea-8b21-1f3674cf9c18.png)

**Comment by LievenDeFoor** [comment]
Strange, that's not what I'm seeing...
The multi line comment takes the color from the settings, but the single line comment seems to take the default color...
![image](https://user-images.githubusercontent.com/8639525/76740045-834a4400-676d-11ea-8448-70081aa8b6a4.png)

**Comment by LievenDeFoor** [comment]
Hi Lars, could you reproduce the above?

**Comment by lneumeier** [comment]
No, but I may have found the reason for this issue. I will add this potential fix for the next release.

**Comment by lneumeier** [comment]
Fixed in 9.3.2, there is now a preference for single line color.
