### ISSUE TITLE
Multi-line selection issues

### ISSUE THREAD

**Issue by mikefechner** [omecra/de.omecra.oedt.updatesite#87]
https://youtu.be/8df7wfb07LU

After selecting multi-line text two issues:

a) while the multi-line selection is active, the first line selection starts at the begin of the line, not where I actually started the selection in that line.

b) when I click outside the selection, the text is supposed to be unselected - however a small fragment of the selected text remains on the first line.

**Comment by lneumeier** [comment]
What eclipse version are you using?

**Comment by mikefechner** [comment]
Vanilla OpenEdge 12.1. Is that 4.3.1 or so?

**Comment by lneumeier** [comment]
PDSOE 12.1 uses Eclipse 4.9. I'm not able to reproduce this issue. Do you have installed additional plug-ins?

**Comment by mikefechner** [comment]
![image](https://user-images.githubusercontent.com/13220627/76821907-9f062680-680f-11ea-85a1-0caa1faa0736.png)

[pdsoe-installation-details-12.1.txt](https://github.com/omecra/de.omecra.oedt.updatesite/files/4341465/pdsoe-installation-details-12.1.txt)
