### ISSUE TITLE
Dependency compile seems to miss class that became enum

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#88]
I've now had it in two of my workspaces:
A class that used to be a regular class inheriting from Consultingwerk.Enum to mimic the behavior of an Enum before Progress added this to the language has now become an actual Enum (DEFINE ENUM).
On pulling the changes from Git and triggering a dependency build, the class/enum is not recompiled and as such depending sources don't compile either.
Manually compiling the enum and then doing a "Compile Error Files" works...

**Comment by lneumeier** [comment]
I will look into it.

**Comment by lneumeier** [comment]
Fixed in 9.4.0
