### ISSUE TITLE
Correct Using changes FROM ASSEMBLY to FROM PROPATH.

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#89]
Using the new/experimental Using-engine I experienced that doing a "Correct Using" (CTRL-U) using statements that had FROM ASSEMBLY get changed to FROM PROPATH.

**Comment by lneumeier** [comment]
Thank you for your feedback. I look into it.

**Comment by lneumeier** [comment]
Verified and fixed for the next release.

**Comment by LievenDeFoor** [comment]
Great, what's the expected release date for 9.3.1?

**Comment by lneumeier** [comment]
Thursday evening.
