### ISSUE TITLE
Enhancement request : Disable refresh during build

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#91]
I'm trying to solve following PDSOE performance issue

During OEDT build each save of rcode causes the workspace to refresh, see animated gif
![buldtriggersrefresh](https://user-images.githubusercontent.com/1312691/81544100-52eee280-9377-11ea-8669-3560103d7f55.gif)

This is because we use "refresh using native hooks"
![image](https://user-images.githubusercontent.com/1312691/81544337-ae20d500-9377-11ea-952c-b37c9a68f893.png)

Currently we manually change this setting during builds but it frequently occurs that we forget to re-enable it after the build.

Would it be possible to disable native polling during build and re-enable it afterwards ?
I'm not sure if my request is feasible but I'm hoping it's low hanging fruit.
Found this SO question but I don't know if the answer is useful 
https://stackoverflow.com/questions/26113234/how-to-change-eclipse-preferences-programmatically

**Comment by lneumeier** [comment]
I can block updates to a dedicated rcode output folder, like rcode, which will suspend the refresh job until the compilation is done. But this would only work for propath configurations which uses such a dedicated rcode folder.

I look into the preference option.

**Comment by lneumeier** [comment]
Added in 9.3.2.
