### ISSUE TITLE
Handle type annotation

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#93]
I have an object with a property:

    DEFINE PUBLIC PROPERTY DatasetHandle AS HANDLE NO-UNDO
    GET.
    
It would be nice if I could annotate this property with its type (dataset) so I can get intelligent auto-completion when typing MyObject:DatasetHandle: instead of showing all possible handle based attributes/methods.

**Comment by lneumeier** [comment]
Added `@Dataset.`, `@Temptable.`and `@Buffer.` evaluation for code assist.
