### ISSUE TITLE
No autocompletion for parameter buffer fields

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#96]
There is no autocompletion for field names of a buffer defined as parameter.

define parameter buffer pbTableName for TableName.

![image](https://user-images.githubusercontent.com/1312691/83623327-7c271b00-a591-11ea-9342-af26abfd86cf.png)

If I define the same buffer without parameter there is autocompletion.

![image](https://user-images.githubusercontent.com/1312691/83623293-70d3ef80-a591-11ea-9b60-8e41c6d2f4d7.png)

OE 12.2
OEDT 9.3.3

**Comment by lneumeier** [comment]
@cverbiest 

I am having trouble to reproduce your error. 
![buffer-parameter](https://user-images.githubusercontent.com/39283158/83967057-84979280-a8be-11ea-8d5e-b0687f7328b3.png)

Is this error specific to a single file or does this error show up on multiple files?

**Comment by cverbiest** [comment]
It seems to be specific to where the file is located.
It's in a folder that is excluded from build.  If I move the file to a different folder completion works.

I can't reproduce it on a simple sport2000 project, even with folders excluded from build, completion keeps working on this source

```
/*------------------------------------------------------------------------
    File        : omecra_case_96.p
  ----------------------------------------------------------------------*/
block-level on error undo, throw.

procedure Testproc:
    define parameter buffer bCustomer for Customer.
    find first bCustomer where bCustomer.
    find first Customer where customer.
end procedure.
```

**Comment by lneumeier** [comment]
Thank you for your feedback. I will look into it, hopefully I find something that is causing this issue.
