### ISSUE TITLE
Auto complete for LENGTH function is not showing overloaded variants

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#97]
Currently auto complete for then LENGTH function only shows the variant that takes a character as single input.
There are overloads taking a raw or blob as well + an overload that takes a second parameter "type".

**Comment by LievenDeFoor** [comment]
Idem for SUBSTRING, which can also take a "type" as fourth parameter

**Comment by lneumeier** [comment]
This is currently a known limitation. At the time I implemented code assistance for keywords (functions, statements, etc...) I decided to use the minimum of parameters/arguments.

**Comment by lneumeier** [comment]
Added in 9.3.4.
